# Generated by Django 4.0.2 on 2022-03-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('postNum', models.IntegerField()),
                ('upvoteCount', models.IntegerField()),
                ('downvoteCount', models.IntegerField()),
                ('ratedBodyID', models.IntegerField()),
                ('rate_stars', models.IntegerField()),
            ],
        ),
    ]
