# Generated by Django 4.0.2 on 2022-03-17 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateMySchoolApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='postcontent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='downvoteCount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postNum',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rate_stars',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ratedBodyID',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvoteCount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
    ]
