# Generated by Django 4.0.2 on 2022-03-17 04:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rateMySchoolApp', '0002_rename_content_post_postcontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downvoteCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rate_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='upvoteCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 4, 10, 30, 699030, tzinfo=utc)),
        ),
    ]
