# Generated by Django 4.0.2 on 2022-03-17 04:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rateMySchoolApp', '0003_post_downvotecount_post_rate_stars_post_upvotecount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 4, 58, 0, 991729, tzinfo=utc)),
        ),
    ]
