# Generated by Django 4.0.2 on 2022-03-17 05:04

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('rateMySchoolApp', '0006_alter_post_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='firstName',
            field=models.CharField(default=sqlalchemy.sql.expression.null, max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='lastName',
            field=models.CharField(default=sqlalchemy.sql.expression.null, max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
