# Generated by Django 4.0.2 on 2022-03-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMySchoolApp', '0007_post_firstname_post_lastname_alter_post_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
