# Generated by Django 4.0.2 on 2022-03-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMySchoolApp', '0008_post_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country_code', models.IntegerField()),
                ('overall_rating', models.IntegerField()),
            ],
        ),
    ]
